### ISSUE TITLE
docsonnet not finding nested doc-strings

### ISSUE THREAD

**Issue by nabadger** [jsonnet-libs/docsonnet#15]
Hi,

Would you be able to confirm whether this is expected to work?

I find that any object/function under `new()` does not get picked up by `docsonnet` , i.e. there's no `inside_object` - was hoping it would also get rendered into markdown :)

```jsonnet
local d = import 'doc-util/main.libsonnet';
{
  // package declaration
  '#': d.pkg(
    name='myapp',
    url='...',
    help='`myapp` implements a ...',
  ),

  '#outside_object': d.obj('This works and docsonnet renders it'),
  outside_object+:: {
    foo: {},
  },

  '#new':: d.fn(help='new returns an instance of myapp',
                args=[
                  d.arg(name='config', type=d.T.string),
                  d.arg(name='name', type=d.T.string),
                ]),

  new(config, name)::
    {
      '#inside_object': d.obj('This does not get rendered by docsonnet'),
      inside_object+:: {
        foo: {},
      },
    },
}
```

renders to

---
permalink: /
---

# package myapp

```jsonnet
local myapp = import "..."
```

`myapp` implements a ...

## Index

* [`fn new(config, name)`](#fn-new)
* [`obj outside_object`](#obj-outside_object)
  

### fn new

```ts
new(config, name)
```

new returns an instance of myapp

## obj outside_object

This works and docsonnet renders it

**Comment by Duologic** [comment]
As it's not reading the AST but simply executing the jsonnet, it would be required to execute `new()` somehow, without knowing the right values for the arguments, this becomes virtually impossible.

I'm going to close this as won't fix.
